# version: "3.8"

services:
  user-db:
    image: postgres:17
    container_name: user-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user_service
      POSTGRES_PASSWORD: user1234
      POSTGRES_DB: userdb
      TZ: "Asia/Kolkata"
    ports:
      - "5333:5432"
    volumes:
      - user_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_service"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  order-db:
    image: postgres:17
    container_name: order-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: order_service
      POSTGRES_PASSWORD: user1234
      POSTGRES_DB: orderdb
      TZ: "Asia/Kolkata"
    ports:
      - "5334:5432"
    volumes:
      - order_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U order_service" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: demo-project-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: demo-project-zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: demo-project-kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # internal listener (inside Docker)
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092

      # advertised listener (for other containers)
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      # (Optional) allow auto-topic creation
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

    ports:
      - "9092:9092"
    networks:
      - app-network

  user-service:
    build:
      context: ./MicroServices/user-service
      dockerfile: Dockerfile
    container_name: user-service
    restart: unless-stopped
    depends_on:
      user-db:
        condition: service_healthy
      # redis:
      #   condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/userdb
      SPRING_DATASOURCE_USERNAME: user_service
      SPRING_DATASOURCE_PASSWORD: user1234
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_PROFILES_ACTIVE: docker
      TZ: "Asia/Kolkata"
    ports:
      - "8081:8080"
    networks:
      - app-network

  order-service:
    build:
      context: ./MicroServices/order-service
      dockerfile: Dockerfile
    container_name: order-service
    restart: unless-stopped
    depends_on:
      order-db:
        condition: service_healthy
      # redis:
      #   condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-db:5432/orderdb
      SPRING_DATASOURCE_USERNAME: order_service
      SPRING_DATASOURCE_PASSWORD: user1234
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_PROFILES_ACTIVE: docker
      TZ: "Asia/Kolkata"
    ports:
      - "8082:8080"
    networks:
      - app-network

volumes:
  user_pgdata:
  order_pgdata:
  redisdata:

networks:
  app-network:
    driver: bridge
