spring.datasource.url=jdbc:postgresql://db:5432/mydb
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:anubhab09}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:anubhab1234}

spring.redis.host=${SPRING_REDIS_HOST:redis}
spring.redis.port=${SPRING_REDIS_PORT:6379}

# optional: final tuning
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.cache.type=redis

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
