spring.application.name=demo-project-1
spring.datasource.url=jdbc:postgresql://localhost:5332/mydb
spring.datasource.username=anubhab09
spring.datasource.password=anubhab1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# DataSource / HikariCP
spring.datasource.hikari.data-source-properties.stringtype=unspecified
spring.datasource.hikari.data-source-properties.TCPKeepAlive=true
spring.datasource.hikari.data-source-properties.serverTimezone=Asia/Kolkata

# Redis
spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6379

logging.level.org.springframework.cache=DEBUG
logging.level.org.springframework.data.redis=INFO