spring.datasource.url=jdbc:postgresql://inventory-db:5432/inventorydb
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:inventory_service}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.redis.host=${SPRING_REDIS_HOST:redis}
spring.redis.port=${SPRING_REDIS_PORT:6379}

# optional: final tuning
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.cache.type=redis

# run the app on container port 8080 (docker-compose maps host ports)
server.port=${SERVER_PORT:8080}

management.endpoints.web.exposure.include=health,info,metrics,prometheus,threaddump,loggers
management.endpoint.health.show-details=always
management.metrics.tags.environment=docker-local
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true

# Kafka consumer (JSON -> POJO)
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=inventory-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=com.anubhab09.inventory_service.event.OrderCreatedEvent
spring.kafka.consumer.properties.spring.json.use.type.headers=false
# topic (optional)
kafka.topic.order-created=order-created

# Admin (dev)
spring.kafka.admin.auto-create=true
spring.kafka.admin.fail-fast=false